export const RESET_ERROR = "RESET_ERROR";

export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAILURE = "USER_FETCH_FAILURE";

export const SET_USER_DETAILS = "SET_USER_DETAILS";
